<a href="https://colab.research.google.com/github/cesaroliveiragoes/Statistics-for-Data-Science/blob/main/class_10_Estatistica_Descritiva_(18_08_2023).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Estatística Descritiva

## Módulos

In [ ]:
import numpy as np
import pandas as pd

## Carregar dados

In [ ]:
dados_paises = pd.read_csv('dados_1997_2011_paises_csv.csv', sep = ';', decimal = ',', encoding='latin1')

## Métricas

### min, max, mean - Slide 6

In [ ]:
dados_paises.groupby('pais') \
            .agg(min_idh = pd.NamedAgg('idh', 'min'),
                 max_idh = pd.NamedAgg('idh', 'max'),
                 media_idh = pd.NamedAgg('idh', 'mean')) \
            .reset_index()

              pais  min_idh  max_idh  media_idh
0         Alemanha   0.8466   0.9050   0.882880
1        Austrália   0.8958   0.9290   0.914507
2           Brasil   0.6464   0.7180   0.684653
3          Bélgica   0.8628   0.8860   0.876107
4           Canadá   0.8736   0.9080   0.890480
5            China   0.5598   0.6870   0.625240
6        Cingapura   0.7404   0.8660   0.821587
7           Coréia   0.8078   0.8970   0.856907
8          Espanha   0.8162   0.8780   0.852427
9   Estados Unidos   0.8886   0.9130   0.900947
10          França   0.8298   0.8840   0.861773
11         Holanda   0.8724   0.9100   0.891320
12          Itália   0.8070   0.8740   0.848000
13           Japão   0.8572   0.9010   0.881360
14          México   0.6916   0.7700   0.736080
15     Reino Unido   0.8228   0.8630   0.846440
16          Rússia   0.6814   0.7550   0.718520
17   África do Sul   0.5990   0.6328   0.612240
18           Índia   0.4466   0.5470   0.495680

### Moda - Slide 7

In [ ]:
dados_paises.groupby('pais')['idh'] \
            .apply(lambda x: x.mode().iloc[0]) \
            .to_frame() \
            .reset_index()

              pais     idh
0         Alemanha  0.8466
1        Austrália  0.8958
2           Brasil  0.6464
3          Bélgica  0.8628
4           Canadá  0.9030
5            China  0.5598
6        Cingapura  0.7404
7           Coréia  0.8078
8          Espanha  0.8162
9   Estados Unidos  0.8886
10          França  0.8298
11         Holanda  0.8724
12          Itália  0.8070
13           Japão  0.8572
14          México  0.6916
15     Reino Unido  0.8600
16          Rússia  0.6814
17   África do Sul  0.5990
18           Índia  0.4466

### Median - Slide 9

In [ ]:
dados_paises.groupby('pais') \
            .agg(median_idh = pd.NamedAgg('idh', 'median')) \
            .reset_index()

              pais  median_idh
0         Alemanha      0.8888
1        Austrália      0.9156
2           Brasil      0.6866
3          Bélgica      0.8754
4           Canadá      0.8894
5            China      0.6240
6        Cingapura      0.8282
7           Coréia      0.8588
8          Espanha      0.8534
9   Estados Unidos      0.9010
10          França      0.8644
11         Holanda      0.8884
12          Itália      0.8538
13           Japão      0.8824
14          México      0.7364
15     Reino Unido      0.8506
16          Rússia      0.7182
17   África do Sul      0.6100
18           Índia      0.4954

### Percentile

- Exemplo numpy - Slide 13

- O numpy utiliza esta interpolação como default

In [ ]:
'https://stackoverflow.com/questions/60467081/linear-interpolation-in-numpy-quantile'

def my_quantile(array, q):
    n = len(array)
    index = (n - 1) * q
    if int(index) == index:  # has no fractional part
        return array[index]
    fraction = index - int(index)
    left = int(index)
    right = left + 1
    i, j = array[left], array[right]
    return i + (j - i) * fraction

In [ ]:
dados = [1, 1, 1, 2, 2, 3, 4, 4, 7, 8, 9]

In [ ]:
np.quantile(dados, 0.35)

2.0

- Exemplo pandas - Slide 14

In [ ]:
dados_paises.groupby('pais')['idh'] \
            .apply(lambda x: x.quantile([0.05, 0.95])) \
            .to_frame() \
            .reset_index() \
            .rename(columns={'level_1': 'percentil'})

              pais  percentil      idh
0         Alemanha       0.05  0.85066
1         Alemanha       0.95  0.90360
2        Austrália       0.05  0.89818
3        Austrália       0.95  0.92760
4           Brasil       0.05  0.65074
5           Brasil       0.95  0.71590
6          Bélgica       0.05  0.86588
7          Bélgica       0.95  0.88530
8           Canadá       0.05  0.87486
9           Canadá       0.95  0.90730
10           China       0.05  0.56638
11           China       0.95  0.68350
12       Cingapura       0.05  0.75454
13       Cingapura       0.95  0.86460
14          Coréia       0.05  0.81298
15          Coréia       0.95  0.89490
16         Espanha       0.05  0.82152
17         Espanha       0.95  0.87660
18  Estados Unidos       0.05  0.89056
19  Estados Unidos       0.95  0.90950
20          França       0.05  0.83358
21          França       0.95  0.88330
22         Holanda       0.05  0.87464
23         Holanda       0.95  0.90930
24          Itália       0.05  0.81120
25          Itália       0.95  0.87330
26           Japão       0.05  0.85972
27           Japão       0.95  0.89960
28          México       0.05  0.69776
29          México       0.95  0.76790
30     Reino Unido       0.05  0.82518
31     Reino Unido       0.95  0.86230
32          Rússia       0.05  0.68364
33          Rússia       0.95  0.75220
34   África do Sul       0.05  0.60040
35   África do Sul       0.95  0.62888
36           Índia       0.05  0.44996
37           Índia       0.95  0.54350

- Ajustes adicionais

In [ ]:
percentis = dados_paises.groupby('pais')['idh'] \
                        .apply(lambda x: x.quantile([0.05, 0.95])) \
                        .to_frame() \
                        .reset_index() \
                        .rename(columns={'level_1': 'percentil'})

In [ ]:
percentis.pivot(index='pais', columns='percentil', values='idh') \
         .reset_index() \
         .rename(columns={0.05:'p_5', 0.95:'p_95'})

percentil            pais      p_5     p_95
0                Alemanha  0.85066  0.90360
1               Austrália  0.89818  0.92760
2                  Brasil  0.65074  0.71590
3                 Bélgica  0.86588  0.88530
4                  Canadá  0.87486  0.90730
5                   China  0.56638  0.68350
6               Cingapura  0.75454  0.86460
7                  Coréia  0.81298  0.89490
8                 Espanha  0.82152  0.87660
9          Estados Unidos  0.89056  0.90950
10                 França  0.83358  0.88330
11                Holanda  0.87464  0.90930
12                 Itália  0.81120  0.87330
13                  Japão  0.85972  0.89960
14                 México  0.69776  0.76790
15            Reino Unido  0.82518  0.86230
16                 Rússia  0.68364  0.75220
17          África do Sul  0.60040  0.62888
18                  Índia  0.44996  0.54350

### Quantiles

In [ ]:
dados_paises.groupby('pais')['idh'] \
            .apply(lambda x: x.quantile([0.25, 0.5, 0.75])) \
            .to_frame() \
            .reset_index() \
            .rename(columns={'level_1': 'percentil'})

              pais  percentil     idh
0         Alemanha       0.25  0.8671
1         Alemanha       0.50  0.8888
2         Alemanha       0.75  0.9005
3        Austrália       0.25  0.9072
4        Austrália       0.50  0.9156
5        Austrália       0.75  0.9230
6           Brasil       0.25  0.6677
7           Brasil       0.50  0.6866
8           Brasil       0.75  0.7025
9          Bélgica       0.25  0.8733
10         Bélgica       0.50  0.8754
11         Bélgica       0.75  0.8810
12          Canadá       0.25  0.8803
13          Canadá       0.50  0.8894
14          Canadá       0.75  0.9015
15           China       0.25  0.5925
16           China       0.50  0.6240
17           China       0.75  0.6605
18       Cingapura       0.25  0.8044
19       Cingapura       0.50  0.8282
20       Cingapura       0.75  0.8525
21          Coréia       0.25  0.8336
22          Coréia       0.50  0.8588
23          Coréia       0.75  0.8835
24         Espanha       0.25  0.8408
25         Espanha       0.50  0.8534
26         Espanha       0.75  0.8685
27  Estados Unidos       0.25  0.8975
28  Estados Unidos       0.50  0.9010
29  Estados Unidos       0.75  0.9055
30          França       0.25  0.8483
31          França       0.50  0.8644
32          França       0.75  0.8780
33         Holanda       0.25  0.8828
34         Holanda       0.50  0.8884
35         Holanda       0.75  0.9030
36          Itália       0.25  0.8286
37          Itália       0.50  0.8538
38          Itália       0.75  0.8695
39           Japão       0.25  0.8698
40           Japão       0.50  0.8824
41           Japão       0.75  0.8945
42          México       0.25  0.7203
43          México       0.50  0.7364
44          México       0.75  0.7580
45     Reino Unido       0.25  0.8352
46     Reino Unido       0.50  0.8506
47     Reino Unido       0.75  0.8580
48          Rússia       0.25  0.6944
49          Rússia       0.50  0.7182
50          Rússia       0.75  0.7445
51   África do Sul       0.25  0.6049
52   África do Sul       0.50  0.6100
53   África do Sul       0.75  0.6175
54           Índia       0.25  0.4653
55           Índia       0.50  0.4954
56           Índia       0.75  0.5250

- Ajustes adicionais

In [ ]:
quartis = dados_paises.groupby('pais')['idh'] \
                      .apply(lambda x: x.quantile([0.25, 0.5, 0.75])) \
                      .to_frame() \
                      .reset_index() \
                      .rename(columns={'level_1': 'percentil'})

In [ ]:
quartis.pivot(index='pais', columns='percentil', values='idh') \
       .reset_index() \
       .rename(columns={0.25:'p_25', 0.5:'p_5', 0.75:'p_75'})

percentil            pais    p_25     p_5    p_75
0                Alemanha  0.8671  0.8888  0.9005
1               Austrália  0.9072  0.9156  0.9230
2                  Brasil  0.6677  0.6866  0.7025
3                 Bélgica  0.8733  0.8754  0.8810
4                  Canadá  0.8803  0.8894  0.9015
5                   China  0.5925  0.6240  0.6605
6               Cingapura  0.8044  0.8282  0.8525
7                  Coréia  0.8336  0.8588  0.8835
8                 Espanha  0.8408  0.8534  0.8685
9          Estados Unidos  0.8975  0.9010  0.9055
10                 França  0.8483  0.8644  0.8780
11                Holanda  0.8828  0.8884  0.9030
12                 Itália  0.8286  0.8538  0.8695
13                  Japão  0.8698  0.8824  0.8945
14                 México  0.7203  0.7364  0.7580
15            Reino Unido  0.8352  0.8506  0.8580
16                 Rússia  0.6944  0.7182  0.7445
17          África do Sul  0.6049  0.6100  0.6175
18                  Índia  0.4653  0.4954  0.5250

### Desvio - Slide 20

In [ ]:
media_paises = dados_paises.groupby('pais') \
                           .agg(media_idh = pd.NamedAgg('idh', 'mean')) \
                           .reset_index()

In [ ]:
dados_paises = dados_paises.merge(media_paises, on = 'pais', how = 'left')

In [ ]:
dados_paises['desvio_idh'] = dados_paises['idh'] - dados_paises['media_idh']

In [ ]:
dados_paises[['pais', 'ano', 'idh', 'desvio_idh']]

              pais   ano     idh  desvio_idh
0    África do Sul  1997  0.6328     0.02056
1    África do Sul  1998  0.6272     0.01496
2    África do Sul  1999  0.6216     0.00936
3    África do Sul  2000  0.6160     0.00376
4    África do Sul  2001  0.6126     0.00036
..             ...   ...     ...         ...
280    Reino Unido  2007  0.8560     0.00956
281    Reino Unido  2008  0.8600     0.01356
282    Reino Unido  2009  0.8600     0.01356
283    Reino Unido  2010  0.8620     0.01556
284    Reino Unido  2011  0.8630     0.01656

[285 rows x 4 columns]

### Desvio médio - Slide 21

In [ ]:
dados_paises.groupby('pais') \
            .agg(desvio_medio_idh = pd.NamedAgg('desvio_idh', 'mean')) \
            .reset_index()

              pais  desvio_medio_idh
0         Alemanha      1.258253e-16
1        Austrália      1.110223e-16
2           Brasil     -2.220446e-17
3          Bélgica      8.141636e-17
4           Canadá     -3.700743e-17
5            China      1.036208e-16
6        Cingapura      8.881784e-17
7           Coréia      8.141636e-17
8          Espanha      0.000000e+00
9   Estados Unidos      1.184238e-16
10          França     -5.921189e-17
11         Holanda      1.480297e-17
12          Itália     -8.881784e-17
13           Japão     -1.406282e-16
14          México      1.628327e-16
15     Reino Unido      1.332268e-16
16          Rússia      5.181041e-17
17   África do Sul     -7.401487e-18
18           Índia      7.401487e-18

### Desvio médio absoluto - Slide 23

In [ ]:
dados_paises.groupby('pais') \
            .agg(desvio_medio_abs_idh = pd.NamedAgg('idh', 'mad')) \
            .reset_index()

              pais  desvio_medio_abs_idh
0         Alemanha              0.017301
1        Austrália              0.008740
2           Brasil              0.018983
3          Bélgica              0.004848
4           Canadá              0.010219
5            China              0.035243
6        Cingapura              0.029934
7           Coréia              0.025273
8          Espanha              0.015732
9   Estados Unidos              0.005124
10          França              0.015362
11         Holanda              0.010544
12          Itália              0.020507
13           Japão              0.012469
14          México              0.020235
15     Reino Unido              0.011744
16          Rússia              0.022848
17   África do Sul              0.007803
18           Índia              0.029365

### Variância e Desvio Padrão - Slide 25

In [ ]:
dados_paises.groupby('pais') \
            .agg(variancia_idh = pd.NamedAgg('idh', 'var'),
                 dp_idh = pd.NamedAgg('idh', 'std')) \
            .reset_index()

              pais  variancia_idh    dp_idh
0         Alemanha       0.000408  0.020187
1        Austrália       0.000110  0.010485
2           Brasil       0.000517  0.022727
3          Bélgica       0.000041  0.006401
4           Canadá       0.000142  0.011899
5            China       0.001758  0.041928
6        Cingapura       0.001443  0.037984
7           Coréia       0.000886  0.029773
8          Espanha       0.000372  0.019299
9   Estados Unidos       0.000043  0.006558
10          França       0.000328  0.018103
11         Holanda       0.000152  0.012341
12          Itália       0.000563  0.023729
13           Japão       0.000213  0.014602
14          México       0.000607  0.024646
15     Reino Unido       0.000189  0.013745
16          Rússia       0.000698  0.026420
17   África do Sul       0.000096  0.009790
18           Índia       0.001185  0.034417

In [ ]:
dados_paises.columns

Index(['pais', 'ano', 'idh', 'corrupcao_indice', 'competitividade_indice',
       'globalizacao_indice', 'pib', 'populacao', 'media_idh', 'desvio_idh'],
      dtype='object')